apiVersion: v2
name: juicefs-s3-gateway
description: A Helm chart for JuiceFS S3 Gateway
type: application
version: 0.2.0
appVersion: "1.0.0"
home: https://github.com/juicedata/juicefs
sources:
  - https://github.com/juicedata/juicefs
icon: https://s.juicefs.com/static/jfs/logo.svg
maintainers:
  - email: team@juicedata.io
    name: Juicedata Inc
keywords:
  - juicefs
  - s3 gateway
