name: "command-test"

on:
  push:
    branches:
      - 'main'
      - 'release-**'
    paths:
      - '.github/scripts/command/*.sh'
      - '**/command.yml'
  pull_request:
    branches:
      - 'main'
      - 'release-**'
    paths:
      - '.github/scripts/command/*.sh'
      - '**/command.yml'
  schedule:
    - cron:  '30 20 * * *'

  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false

jobs:
  build-matrix:
    runs-on: ubuntu-20.04
    steps:
      - id: set-matrix
        run: |
          echo "github.event_name is ${{github.event_name}}"
          echo "GITHUB_REF_NAME is ${GITHUB_REF_NAME}"
          if [ "${{github.event_name}}" == "schedule"  ]; then
            echo 'meta_matrix=["mysql", "redis", "tikv"]' >> $GITHUB_OUTPUT
          elif [ "${{github.event_name}}" == "pull_request"  ]; then
            echo 'meta_matrix=["mysql", "redis", "tikv"]' >> $GITHUB_OUTPUT
          elif [ "${{github.event_name}}" == "workflow_dispatch"  ]; then
            echo 'meta_matrix=["mysql", "redis", "tikv"]' >> $GITHUB_OUTPUT
          else
            echo 'meta_matrix=["redis"]' >> $GITHUB_OUTPUT
          fi
    outputs:
      meta_matrix: ${{ steps.set-matrix.outputs.meta_matrix }}

  command_test1:
    timeout-minutes: 60
    needs: [build-matrix]
    strategy:
      fail-fast: false
      matrix:
        # meta: [ 'sqlite3', 'redis', 'tikv']
        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Remove unused software
        shell: bash
        run: |
            echo "before remove unused software"
            sudo df -h
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            echo "after remove unused software"
            sudo df -h

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build 
        timeout-minutes: 10
        uses: ./.github/actions/build
  
      - name: Test Gc
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/gc.sh      

      - name: Test Config
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/config.sh
    
      - name: Test acl
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/acl.sh     

      - name: Test Clone
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/clone.sh

      - name: Test fsck
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/fsck.sh 
      
      - name: Test Gateway
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/gateway.sh
      
      - name: Test Debug
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/debug.sh
      
      - name: Test Info
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/info.sh

      - name: Test Format
        if: false
        timeout-minutes: 10
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/format.sh
  
      - name: Log
        if: always()
        run: |
          echo "juicefs log"
          sudo tail -n 1000 /var/log/juicefs.log
          grep "<FATAL>:" /var/log/juicefs.log || true
          
      - name: Setup upterm session
        if: failure() && (github.event.inputs.debug == 'true' || github.run_attempt != 1)
        # if: failure()
        timeout-minutes: 60
        uses: lhotari/action-upterm@v1

  command_test2:
    needs: [build-matrix]
    strategy:
      fail-fast: false
      matrix:
        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Remove unused software
        run: |
            echo "before remove unused software"
            sudo df -h
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            echo "after remove unused software"
            sudo df -h
            
      - name: Build 
        uses: ./.github/actions/build

      - name: Test Quota
        timeout-minutes: 30
        run: |
          sudo META=${{matrix.meta}} .github/scripts/command/quota.sh 

      - name: Log
        if: always()
        run: |
          echo "juicefs log"
          sudo tail -n 1000 /var/log/juicefs.log
          grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true
          
      - name: Setup upterm session
        if: failure() && (github.event.inputs.debug == 'true' || github.run_attempt != 1)
        # if: failure()
        timeout-minutes: 60
        uses: lhotari/action-upterm@v1

  command_test3:
    needs: [build-matrix]
    strategy:
      fail-fast: false
      matrix:
        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build 
        uses: ./.github/actions/build

      - name: Test Graceful upgrade
        timeout-minutes: 30
        run: |
          if [ "${{matrix.meta}}" == "redis" ]; then
            sudo META=${{matrix.meta}} .github/scripts/command/graceful_upgrade.sh
          fi

      - name: Log
        if: always()
        run: |
          if [ "${{matrix.meta}}" == "redis" ]; then
            echo "juicefs log"
            sudo tail -n 1000 /var/log/juicefs.log
            grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true
          fi
          
      - name: Setup upterm session
        if: failure() && (github.event.inputs.debug == 'true' || github.run_attempt != 1)
        # if: failure()
        timeout-minutes: 60
        uses: lhotari/action-upterm@v1

  success-all-test:
    runs-on: ubuntu-latest
    needs: [command_test1, command_test2, command_test3]
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: actions/checkout@v3

      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1

      - name: Send Slack Notification
        if: failure() && github.event_name != 'workflow_dispatch'
        uses: juicedata/slack-notify-action@main
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"

      - name: Success
        if: success()
        run: echo "All Done"
