name: "mysqltestlocal"

on:
  push:
    branches:
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches:
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron:  '50 * * * *'
  workflow_dispatch:

jobs:
  mysqltestsmalltablelocal:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Data Dir
        run: |
          sudo service mysql start
          sudo service mysql status
          sudo mysql -uroot -proot  -e "select @@datadir;"


      - name: Install Sysbench
        run: |
          curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | sudo bash
          sudo apt -y install sysbench
          sudo mysql -uroot -proot -e "create database test;"
          echo "mysql-host=127.0.0.1" >>/tmp/config.cfg
          echo "mysql-port=3306" >>/tmp/config.cfg
          echo "mysql-user=root" >>/tmp/config.cfg
          echo "mysql-password=root" >>/tmp/config.cfg
          echo "mysql-db=test" >>/tmp/config.cfg
          echo "threads=64" >>/tmp/config.cfg
          echo "report-interval=10" >>/tmp/config.cfg
          echo "db-driver=mysql" >>/tmp/config.cfg

      - name: Small Size Table Test
        run: |
          sudo mysql -uroot -proot  -e "use mysql;set global max_prepared_stmt_count = 100000;"
          sudo sysbench --config-file=/tmp/config.cfg oltp_point_select --tables=64 --table-size=100000 prepare
          sudo sysbench --config-file=/tmp/config.cfg oltp_read_only --tables=64 --time=300 --table-size=100000 run
          sudo sysbench --config-file=/tmp/config.cfg oltp_write_only --tables=64 --time=300 --table-size=100000 run
          sudo sysbench --config-file=/tmp/config.cfg oltp_read_write --tables=64 --time=600 --table-size=100000 run
          sudo sysbench --config-file=/tmp/config.cfg oltp_point_select --tables=64 --table-size=100000 cleanup

      - name: Send Slack Notification
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}
          slack-message: "@${{ github.actor}} CI Check ${{ job.status }} on ${{ github.event_name }}\n${{ github.event.pull_request.title || github.event.head_commit.message }} \nhttps://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  
      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1